FROM maven:3.8.5-openjdk-17 AS builder
WORKDIR /app
COPY pom.xml .  
RUN mvn dependency:go-offline -B  
COPY src ./src  
RUN mvn clean package -DskipTests  

# Stage 2: Run the application
FROM openjdk:17-jre-slim AS runtime
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar  
EXPOSE 8080  
ENTRYPOINT ["java", "-jar", "order-service/src/test/java/com/hcltech/poc/order_service
/OrderServiceApplicationTests.java"]
